language: objective-c
osx_image: xcode10.1

before_install:
  - pod repo update --silent
  - gem install xcpretty

install:
  - pod install

script:
  - set -o pipefail && xcodebuild -workspace gasolinapp.xcworkspace -scheme 'gasolinapp' -destination 'platform=iOS Simulator,name=iPhone 7' build test CODE_SIGN_IDENTITY=- | xcpretty -c

