//
//  Assets.swift
//  chicfy
//
//  Generated by SwiftGen with xcassets-swift4.stencil on 06/02/2018.
//  Copyright © 2018 chicfy s.l. All rights reserved.
//

import UIKit.UIImage
typealias Image = UIImage

@available(*, deprecated, renamed: "ImageAsset")
typealias AssetType = ImageAsset

struct ImageAsset {

  fileprivate(set) var name: String

  var image: Image {
    let bundle = Bundle(for: BundleToken.self)
    let image = Image(named: name, in: bundle, compatibleWith: nil)
    guard let result = image else {
      fatalError("Unable to load image named \(name).")
    }

    return result
  }
}

enum Asset {

// swiftlint:disable trailing_comma
  static let allImages: [ImageAsset] = [
  ]
// swiftlint:enable trailing_comma
}

extension Image {

  convenience init!(asset: ImageAsset) {
    let bundle = Bundle(for: BundleToken.self)
    self.init(named: asset.name, in: bundle, compatibleWith: nil)
  }
}

private final class BundleToken {

}
